spring:
  application:
  name: mealapp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mealapp-test
    username: root
    password: ${DB_PASSWORD}
